### ISSUE TITLE
Getting error for browser source

### ISSUE THREAD

**Issue by tomdevlive** [rse/obs-crop-control#1]
I get this error in the OBS Log Viewer:

19:37:26.192: [obs-browser: 'CAM2-Full-CC'] Error: Error: invalid define specification "0:0+0/3860x2160" (https://cdn.jsdelivr.net/npm/vue@3.2.26/dist/vue.global.prod.js:1)

**Comment by rse** [comment]
Should be now fixed by allowing also the "0" in the define specification.
